# -*- coding: utf-8 -*-
"""fire & smoke training.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1cvPJ3KPcHgFBaXHF1gIRcDNNxk6K-mq-
"""

!pip install ultralytics
!pip install roboflow

from roboflow import Roboflow
rf = Roboflow(api_key="X0l6cNc6xrFm0zyx8tkd")
project = rf.workspace("middle-east-tech-university").project("fire-and-smoke-detection-hiwia")
version = project.version(2)
dataset = version.download("yolov8")

from ultralytics import YOLO


model = YOLO("yolov8n.pt")


model.train(
    data=dataset.location + "/data.yaml",
    epochs=20,
    imgsz=512,
    batch=8,
    name="fire_detector_yolov8n",
    workers=4,
    device=0,

    hsv_h=0.02,
    hsv_s=0.7,
    hsv_v=0.4,
    fliplr=0.5,
    translate=0.1,
    scale=0.3,
    shear=0.1,
    mosaic=0.5,
    mixup=0.2
)

metrics = model.val()
metrics